import type { IconType } from 'react-icons'
import {
  LuArrowLeftRight,
  LuBinary,
  LuBox,
  LuBraces,
  LuBrackets,
  LuCalculator,
  LuCalendar,
  LuCalendarClock,
  LuCircleDollarSign,
  LuCircleHelp,
  LuClock,
  LuCode,
  LuFingerprint,
  LuHash,
  LuNetwork,
  LuShapes,
  LuTag,
  LuTextSearch,
  LuToggleLeft,
  LuType,
  LuWaypoints,
} from 'react-icons/lu'

const BY_NAME: Record<string, IconType> = {
  uuid: LuFingerprint,
  int2: LuHash,
  int4: LuHash,
  int8: LuHash,
  oid: LuHash,
  numeric: LuCalculator,
  float4: LuCalculator,
  float8: LuCalculator,
  money: LuCircleDollarSign,
  text: LuType,
  varchar: LuType,
  bpchar: LuType,
  name: LuType,
  citext: LuType,
  bool: LuToggleLeft,
  date: LuCalendar,
  timestamp: LuCalendarClock,
  timestamptz: LuCalendarClock,
  time: LuClock,
  timetz: LuClock,
  interval: LuClock,
  json: LuBraces,
  jsonb: LuBraces,
  bytea: LuBinary,
  bit: LuBinary,
  varbit: LuBinary,
  inet: LuNetwork,
  cidr: LuNetwork,
  macaddr: LuNetwork,
  macaddr8: LuNetwork,
  vector: LuWaypoints,
  halfvec: LuWaypoints,
  sparsevec: LuWaypoints,
  tsvector: LuTextSearch,
  tsquery: LuTextSearch,
  xml: LuCode,
}

/** pg_type.typcategory fallbacks for types not named above. */
const BY_CATEGORY: Record<string, IconType> = {
  A: LuBrackets,
  B: LuToggleLeft,
  D: LuCalendarClock,
  E: LuTag,
  G: LuShapes,
  I: LuNetwork,
  N: LuHash,
  R: LuArrowLeftRight,
  S: LuType,
  T: LuClock,
  U: LuBox,
  V: LuBinary,
}

export function typeIcon(typeName: string, typeCategory: string): IconType {
  if (typeCategory === 'A') return LuBrackets
  return BY_NAME[typeName] ?? BY_CATEGORY[typeCategory] ?? LuCircleHelp
}
